spring:
  application:
    name: product
  mongodb:
    uri: "mongodb://${MONGO_DB_USER:rserraf}:${MONGO_DB_PWD:PDB}@localhost:${MONGO_LOCAL_PORT:27017}/${MONGO_DB_NAME:product_database}?authSource=admin"
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: "product-created-topic"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ecommerce-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # properties:
      #   spring.json.trusted.packages: "com.yourproject.dto" # Important for security

server:
  port: 8082
